### PR TITLE
Dark mode

### LINKED ISSUE #44: Add dark mode
Add dark mode to all pages. I will handle this in a PR tomorrow.

### PR DESCRIPTION
**Pull request by Josmolmor**
closes #44 

https://github.com/user-attachments/assets/c4b9ad93-098e-4011-9c4b-f9561cba7a72

### CODE REVIEW

**Comment by johanguse** [comment]
Would you also be able to add the system mode? The system mode gets the user's OS preferences.....

image

**Comment by johanguse** [comment]
Did you know that already exist a PR for dark mode #45 ?

**Comment by Josmolmor** [comment]
> Would you also be able to add the system mode? The system mode gets the user's OS preferences.....
> 
> image

It already checks for user preference https://github.com/leerob/next-saas-starter/pull/56/commits/d8064dc7811fd87d0b5afc248a05c9b0c90db5d1#diff-0dc1c925c74b340e65c99acb568aebf3f7b1b4074b3591bb570667ebc49b385cR17

**Comment by leerob** [comment]
Going to combine with this PR -> https://github.com/leerob/next-saas-starter/pull/45

I don't want to do a picker, but instead just use the system settings 👍

**Comment by syntaxsurge** [comment]
> Going to combine with this PR -> #45

Why? Their solution is different, and I would say that the solution in this PR is better than the one you mentioned.

**Pull request closed without merging**
