### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by slavingia**

### CODE REVIEW

**Comment by jonkurtis** [comment]
top-notch PR you got right here @slavingia! Appreciate your contributions.

**Comment by slavingia** [comment]
always recommend all engineers start with the smallest code change possible :)

**Review by leerob — APPROVED** [review]
Thank you! And ty ❤️ for Gumroad. That was how I launched my first course, which this repo is a spiritual successor of in a lot of ways.

**Comment by slavingia** [comment]
woooot! that's awesome to hear :D

**Review by preechapon-cmd — APPROVED** [review]

**Pull request merged**
