### PR TITLE
add drizzle-kit push for remote

### PR DESCRIPTION
**Pull request by themre**

### CODE REVIEW

**Comment by leerob** [comment]
`db:migrate` will create the tables, right?

**Comment by themre** [comment]
btw, really nice project, wanted to try one of these for a long time and after this one works really well! (besides this minor bump, could be that I did something stupid).

**Comment by leerob** [comment]
Was it a brand new Supabase database?

**Comment by albertpco** [comment]
@themre are you setting the DB url during pnpm setup? If you do it in post and start adding auth, you'll reach some issues which you might be trying to resolve in post. I may be totally incorrect, but that's what happened when I tried it after setting up (type issues + fkey issues will block drizzle migration from what i did)

**Comment by themre** [comment]
Sorry for late reply. I actually reused existing instance, but deleted all tables before. I also changed pg URL after initial setup, so that might also be the case. Should we then add a troubleshooting section? Where we mention that you could run this push command in case of such issues? Although usually I rather prefer to see such things beforehand than going to troubleshooting section :)

**Comment by leerob** [comment]
Going to close this since it doesn't appear to be strictly needed.

**Pull request closed without merging**
